services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.0.2
    container_name: mealie
    restart: always
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - $DOCKER_VOLUMES/mealie:/app/data
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
      BASE_URL: https://mealie.joshua-m-baker.com

networks:
  default:
      name: caddy_net
      external: true

