version: "3"
services:
  deconz:
    image: deconzcommunity/deconz:stable
    container_name: deconz
    restart: always
    privileged: true
    ports: 
      - 4000:80
      - 4001:443
    volumes:
      - /opt/deconz:/opt/deCONZ
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTA=0
      - DECONZ_DEVICE=/dev/ttyACM0 # This is the USB device that Conbee II is running on.

networks:
  default:
    name: caddy_net
    external: true

