version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    volumes:
      - $DOCKER_VOLUMES/jellyfin/config:/config
      - $DOCKER_VOLUMES/jellyfin/cache:/cache
      - $DOCKER_VOLUMES/jellyfin/media:/media
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.josh-test-server.xyz

networks:
  default:
    name: caddy_net
    external: true
