version: "3.5"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v8.13.8
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: caddy_net
    external: true

